services:
  readarr:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    platform: linux/arm64/v8
    container_name: readarr
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      - ./config/readarr:/config
      - ./library:/books
      - /mnt/torbox:/torbox:ro
      - ./scripts:/scripts:ro
    ports:
      - "8787:8787"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    platform: linux/arm64/v8
    container_name: prowlarr
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  decypharr:
    image: ghcr.io/sirrobot01/decypharr:latest
    platform: linux/arm64/v8
    container_name: decypharr
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      - ./config/decypharr:/app
    ports:
      - "8282:8282"
    restart: unless-stopped
