name = "stremio-schatkamer"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "fb129246b8320afdf211e4367fabcbf3"

[observability]
enabled = true
