services:
  - type: web
    name: scorito-webapp
    runtime: docker
    rootDir: scorito-webapp
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_PIN
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: FOOTBALL_DATA_API_KEY
        sync: false
